// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef JaqUI_h
#define JaqUI_h
#include <FL/Fl.H>
#include "Jaq.h"
#include "JQServo.h"
#include "JQLeg.h"
#include <FL/Fl_Simple_Terminal.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern void openComCB(Fl_Button*, void*);
#include <FL/Fl_Input.H>
extern Fl_Input *wComName;
extern void testComCB(Fl_Button*, void*);
extern void closeComCB(Fl_Button*, void*);
extern Fl_Simple_Terminal *wTerminal;
extern void servosPowerOnCB(Fl_Button*, void*);
extern void servosPowerOffCB(Fl_Button*, void*);
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>
extern void setRawAngleCB(Fl_Value_Slider*, long);
extern Fl_Value_Slider *wRawAngle[12];
extern void calibrateCB(Fl_Button*, void*);
extern void setAngleCB(Fl_Value_Slider*, long);
extern Fl_Value_Slider *wAngle[12];
extern void setPositionCB(Fl_Value_Slider*, long);
extern Fl_Value_Slider *wPosition[12];
extern void setAllZCB(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *wAllZ;
Fl_Double_Window* createMainWindow();
#endif
